language: c

compiler:
  - gcc
  - clang

install:
 - sudo apt-get update
 - sudo apt-get install libreadline6-dev
 - sudo apt-get install libssl-dev
 - sudo apt-get install libevent-dev
 - sudo apt-get install libjansson-dev
 - sudo apt-get install fuse libfuse-dev
 - sudo apt-get install gperf
 
script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

